language: node_js
node_js:
- "lts/*"
before_deploy:
- test $TRAVIS_TEST_RESULT = 0
before_install:
- npm install -g mocha
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
- provider: script
  script: chmod +x ./create-release.sh && ./create-release.sh
  on: master
notifications:
  email: false
sudo: false
env:
  global:
